### 변수 설정
@host = http://localhost:8080
@contentType = application/json
@randomInt = {{$randomInt 1 10000}}


### /api/login - 로그인
POST {{host}}/api/login
Content-Type: {{contentType}}

{
  "username": "admin",
  "password": "1234"
}

### 사용자 생성
POST {{host}}/api/users
Content-Type: {{contentType}}

{
  "username": "testuser-{{randomInt}}",
  "email": "test-{{randomInt}}@example.com",
  "password": "1234",
  "role": "USER"
}

### 모든 사용자 조회
GET {{host}}/api/users

### ID로 사용자 조회
GET {{host}}/api/users/1

### 사용자 이름으로 사용자 조회
GET {{host}}/api/users/username/testuser

### 사용자 정보 수정
PUT {{host}}/api/users/1
Content-Type: {{contentType}}

{
  "username": "updateduser",
  "email": "updated@example.com",
  "password": "newpassword123"
}

### 사용자 삭제
DELETE {{host}}/api/users/1