server:
  port: 8080

spring:
  profiles:
    active:
      - local
  output.ansi.enabled: always
  data:
    web:
      pageable:
        one-indexed-parameters: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate.orm.jdbc.bind: TRACE

jwt:
  secret: v3ryS3cr3tK3yMustB3L0ngEn0ughF0rHMACSHA256! # 32자 이상 권장
  expiration: 86400000 # 1일 (밀리초 단위)