### login
# @name login
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "username": "manager",
    "password": "1234"
}

@auth_token = {{login.response.body.$.token}}

### Get all boards
GET http://localhost:8080/api/boards
Authorization: Bearer {{auth_token}}

### Get board by id
GET http://localhost:8080/api/boards/1
Authorization: Bearer {{auth_token}}

### Create board
POST http://localhost:8080/api/boards
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "title": "New Board",
    "content": "New Content",
    "writer": "user",
    "categoryId": "NOTICE",
    "isVisible": true,
    "isNotice": false,
    "isSecret": false
}

### Update board
PUT http://localhost:8080/api/boards/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "title": "Updated Board",
    "content": "Updated Content",
    "categoryId": "QNA",
    "isVisible": false,
    "isNotice": true,
    "isSecret": true
}

### Delete board
DELETE http://localhost:8080/api/boards/1
Authorization: Bearer {{auth_token}}
